### ISSUE TITLE
Download docker error

### ISSUE THREAD

**Issue by timzaak** [crazy-max/ghaction-setup-docker#41]
The failed job: https://github.com/ForNetCode/fornet/actions/runs/6418961704/job/17427808528

Download docker
  Downloading https://download.docker.com/mac/static/stable/arm64/docker-24.0.6.tgz
Error: Unexpected HTTP response: 404

**Comment by crazy-max** [comment]
Fixed by https://github.com/crazy-max/ghaction-setup-docker/pull/43
