### ISSUE TITLE
Action fail on macOS

### ISSUE THREAD

**Issue by RemHero** [crazy-max/ghaction-setup-docker#70]
#### Steps to reproduce this issue

1.running on macos-latest
2.github action 
`  
name: Set up Docker Buildx       
uses: crazy-max/ghaction-setup-docker@v3
`

#### Expected behaviour
There was no problem running 2 days ago, but today there is a sudden error

#### Actual behaviour
![image](https://github.com/crazy-max/ghaction-setup-docker/assets/80055724/c47177d5-49f7-45c5-8192-31e1a9fcb18e)

### Logs

https://github.com/RemHero/IGinX/actions/runs/8831989490/job/24248373450?pr=134

**Comment by crazy-max** [comment]
Looking at your workflow you're using `macos-latest` https://github.com/RemHero/IGinX/actions/runs/8831989490/workflow?pr=134#L23 which is `macos-14`. This runner is on ARM and doesn't support nested virtualization, see disclaimer (warning) in the README for more info: https://github.com/crazy-max/ghaction-setup-docker?tab=readme-ov-file#about
