### ISSUE TITLE
Action fails to start with failure on ssh.sock

### ISSUE THREAD

**Issue by verdverm** [crazy-max/ghaction-setup-docker#78]
#### Steps to reproduce this issue

Recently updated to the latest version

1. Try and use action on a macos-latest runner

#### Expected behaviour

> Should install like it used to

#### Actual behaviour

> Tell us what happens instead

```
{"level":"debug","msg":"executing ssh for exiting the master: /usr/bin/ssh [ssh -F /dev/null -o IdentityFile=\"/Users/runner/.lima/_config/user\" -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o NoHostAuthenticationForLocalhost=yes -o GSSAPIAuthentication=no -o PreferredAuthentications=publickey -o Compression=no -o BatchMode=yes -o IdentitiesOnly=yes -o Ciphers=\"^aes128-gcm@openssh.com,aes256-gcm@openssh.com\" -o User=runner -o ControlMaster=auto -o ControlPath=\"/Users/runner/.lima/docker-actions-toolkit/ssh.sock\" -o ControlPersist=yes -O exit -p 49206 127.0.0.1]","time":"2024-05-02T03:34:35Z"}
{"error":"failed to execute `ssh -O exit -p 49206 127.0.0.1`, out=\"Control socket connect(/Users/runner/.lima/docker-actions-toolkit/ssh.sock): No such file or directory\\r\\n\": exit status 255","level":"warning","msg":"failed to exit SSH master","time":"2024-05-02T03:34:35Z"}
{"level":"info","msg":"Shutting down QEMU with ACPI","time":"2024-05-02T03:34:35Z"}
{"error":"dial unix /Users/runner/.lima/docker-actions-toolkit/qmp.sock: connect: connection refused","level":"warning","msg":"failed to open the QMP socket \"/Users/runner/.lima/docker-actions-toolkit/qmp.sock\", forcibly killing QEMU","time":"2024-05-02T03:34:35Z"}
{"level":"info","msg":"QEMU has already exited","time":"2024-05-02T03:34:35Z"}
```

### Configuration

* Repository URL (if public): 
* Build URL (if public): https://github.com/hofstadter-io/hof/actions/runs/8917966055/job/24491846313#step:6:297

https://github.com/hofstadter-io/hof/blob/update-cue/.github/workflows/hof.yml#L49

```yml
runs-on: macos-latest
...
      - name: Set up Docker
        uses: crazy-max/ghaction-setup-docker@v3
        with:
          version: v24.0.7
        env:
          SIGN_QEMU_BINARY: "1"
          COLIMA_START_ARGS: --cpus 3 --memory 10 --disk 12
        if: ${{ startsWith( runner.os, 'macos') }}
```

### Logs

https://github.com/hofstadter-io/hof/actions/runs/8917966055/job/24491846313#step:6:297

**Comment by verdverm** [comment]
This might be related to the `macos-latest` now being M1 based?

**Comment by verdverm** [comment]
linking because others are seeing similar in other context, might be helpful: https://github.com/ReactiveCircus/android-emulator-runner/issues/350

**Comment by crazy-max** [comment]
> This might be related to the `macos-latest` now being M1 based?

Yes this related to https://github.com/crazy-max/ghaction-setup-docker/pull/53

See disclaimer in the README: https://github.com/crazy-max/ghaction-setup-docker/blob/bca5e4d3e252bb47ebed85515713050e55f7eb15/README.md?plain=1#L12-L17
